ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 1.5
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
    GPU_GPU: True
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    POSITION: [0, 1.25, 0]
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    POSITION: [0, 1.25, 0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    POSITION: [0, 1.25, 0]
